# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import morel_pb2 as morel__pb2


class MorelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthenticationValidator = channel.unary_unary(
                '/Morel/AuthenticationValidator',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=morel__pb2.AuthenticationAnswer.FromString,
                )


class MorelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthenticationValidator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MorelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthenticationValidator': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticationValidator,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=morel__pb2.AuthenticationAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Morel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Morel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthenticationValidator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Morel/AuthenticationValidator',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            morel__pb2.AuthenticationAnswer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
